### ISSUE TITLE
6월 노선 정보 페이지

### ISSUE THREAD

**Issue by thechunsik** [open-transit/ourbus-web#4]
- [x] Parse에 6월 노선 정보 업데이트 하기
- [x] Parse 연동 및 데이터 바인딩
- [x] 최종 UI

**Comment by thechunsik** [comment]
@joohyuck 6월 노선 정보 정류장별 시간이랑 출발/도착 시간 나오는 대로 파스에 업데이트 부탁합니다~!

**Comment by joohyuck** [comment]
@thechunsik 옙!

**Comment by thechunsik** [comment]
@joohyuck  업뎃되면 체크부탁해!
